#application.yml
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: uat
---

spring:
  application:
    name: turborJob
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  main:
    banner-mode : off
    sources : com.turborvip.core
  servlet:
    multipart:
      max-file-size = 10MB
      max-request-size = 10MB
  output:
    ansi:
      enabled: ALWAYS
  graphql:
    servlet:
      maxQueryDepth: 100
    graphiql:
      enabled: true
    playground:
      enabled: true
      mapping: /playground